version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: circleci/buildpack-deps:xenial-scm-dind
    resource_class: xlarge
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t titusoss/titus-executor-builder hack/builder
          