version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:xenial-scm-dind
    environment:
      - SHORT_CIRCUIT_QUITELITE: true
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Builder Image"
          command: |
            make builder
