version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    resource_class: xlarge
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command:
            make builder