version: 2
jobs:
  builder:
    docker:
      - image: docker:17.05.0-ce-git
    resource_class: xlarge
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t titusoss/titus-executor-builder hack/builder
  test:
    docker:
      - image: circleci/1.10.1-stretch
    resource_class: xlarge
    working_directory: /go/src/github.com/Netflix/titus-executor
    steps:
      - checkout
      - run: |
          make test-standalone
          make validate

workflows:
  version: 2
  build_and_test:
    job:
      - builder
      - test